[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
macroquad = "0.3"
bincode = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"