[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
macroquad = "0.4"
image = "0.25.1" 
shared = { path = "../shared" }